// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: air_quality

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenStart
void ui_ScreenStart_screen_init(void);
lv_obj_t *ui_ScreenStart;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label5;


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t *ui_ScreenMain;
lv_obj_t *ui_PanelMain;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_LabelDate;
lv_obj_t *ui_LabelTime;
lv_obj_t *ui_LabelIp;
lv_obj_t *ui_LabelWifi;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_ArcFan;
lv_obj_t *ui_LabelFan;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label3;
lv_obj_t *ui_LabelPm;
lv_obj_t *ui_Panel4;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;


// SCREEN: ui_ScreenNtpConf
void ui_ScreenNtpConf_screen_init(void);
lv_obj_t *ui_ScreenNtpConf;
lv_obj_t *ui_TextAreaNtp;
lv_obj_t *ui_DropdownNtp;
lv_obj_t *ui_Keyboard2;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label4;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label10;


// SCREEN: ui_ScreenWifiConf
void ui_ScreenWifiConf_screen_init(void);
lv_obj_t *ui_ScreenWifiConf;
void ui_event_ButtonWifiSave( lv_event_t * e);
lv_obj_t *ui_ButtonWifiSave;
lv_obj_t *ui_Label7;
void ui_event_ButtonWifiBack( lv_event_t * e);
lv_obj_t *ui_ButtonWifiBack;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Keyboard1;
lv_obj_t *ui_DropdownWifiSsid;
lv_obj_t *ui_TextAreaWifiPass;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;


// SCREEN: ui_ScreenInfo
void ui_ScreenInfo_screen_init(void);
lv_obj_t *ui_ScreenInfo;
lv_obj_t *ui_LabelInfo;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_ScreenNtpConf, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenNtpConf_screen_init);
      _ui_screen_delete( &ui_ScreenMain);
      call_screen_ntp_config( e );
}
}
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      call_screen_wifi_config( e );
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
      _ui_screen_delete( &ui_ScreenNtpConf);
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      save_ntp_config( e );
}
}
void ui_event_ButtonWifiSave( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      save_wifi_config( e );
}
}
void ui_event_ButtonWifiBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
      _ui_screen_delete( &ui_ScreenWifiConf);
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      refresh_wifi_list( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenStart_screen_init();
ui_ScreenMain_screen_init();
ui_ScreenNtpConf_screen_init();
ui_ScreenWifiConf_screen_init();
ui_ScreenInfo_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenStart);
}
