// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: air_quality

#ifndef _AIR_QUALITY_UI_H
#define _AIR_QUALITY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenStart
void ui_ScreenStart_screen_init(void);
extern lv_obj_t *ui_ScreenStart;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label5;
// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_PanelMain;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_LabelDate;
extern lv_obj_t *ui_LabelTime;
extern lv_obj_t *ui_LabelIp;
extern lv_obj_t *ui_LabelWifi;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_ArcFan;
extern lv_obj_t *ui_LabelFan;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_LabelPm;
extern lv_obj_t *ui_Panel4;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
// SCREEN: ui_ScreenNtpConf
void ui_ScreenNtpConf_screen_init(void);
extern lv_obj_t *ui_ScreenNtpConf;
extern lv_obj_t *ui_TextAreaNtp;
extern lv_obj_t *ui_DropdownNtp;
extern lv_obj_t *ui_Keyboard2;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label10;
// SCREEN: ui_ScreenWifiConf
void ui_ScreenWifiConf_screen_init(void);
extern lv_obj_t *ui_ScreenWifiConf;
void ui_event_ButtonWifiSave( lv_event_t * e);
extern lv_obj_t *ui_ButtonWifiSave;
extern lv_obj_t *ui_Label7;
void ui_event_ButtonWifiBack( lv_event_t * e);
extern lv_obj_t *ui_ButtonWifiBack;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_DropdownWifiSsid;
extern lv_obj_t *ui_TextAreaWifiPass;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
// SCREEN: ui_ScreenInfo
void ui_ScreenInfo_screen_init(void);
extern lv_obj_t *ui_ScreenInfo;
extern lv_obj_t *ui_LabelInfo;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1537150334);   // assets/air-pollution.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets/wifi.png
LV_IMG_DECLARE( ui_img_1215880664);   // assets/air-pollution (1).png
LV_IMG_DECLARE( ui_img_schedule_png);   // assets/schedule.png
LV_IMG_DECLARE( ui_img_357916539);   // assets/internet-setting.png
LV_IMG_DECLARE( ui_img_534919753);   // assets/wifi (2).png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
