// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: air_quality

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void call_screen_ntp_config(lv_event_t * e);
void call_screen_wifi_config(lv_event_t * e);
void save_ntp_config(lv_event_t * e);
void save_wifi_config(lv_event_t * e);
void refresh_wifi_list(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
