// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: air_quality

#include "ui.h"

void ui_ScreenMain_screen_init(void)
{
ui_ScreenMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScreenMain,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_ScreenMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_PanelMain = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_PanelMain, 476);
lv_obj_set_height( ui_PanelMain, 270);
lv_obj_set_align( ui_PanelMain, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelMain,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_PanelMain, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMain, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_PanelMain);
lv_obj_set_width( ui_Panel2, 470);
lv_obj_set_height( ui_Panel2, 42);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, -96 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDate = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_LabelDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelDate, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDate,"00/00/0000");
lv_obj_set_style_text_font(ui_LabelDate, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTime = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_LabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTime,"00:00:00");
lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelIp = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_LabelIp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelIp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelIp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelIp,"000.000.0.0");
lv_obj_set_style_text_font(ui_LabelIp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWifi = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_LabelWifi, 42);
lv_obj_set_height( ui_LabelWifi, 29);
lv_obj_set_x( ui_LabelWifi, 80 );
lv_obj_set_y( ui_LabelWifi, 55 );
lv_obj_set_align( ui_LabelWifi, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LabelWifi,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_LabelWifi, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_LabelWifi,"");
lv_obj_set_style_bg_img_src( ui_LabelWifi, &ui_img_wifi_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_LabelWifi, lv_color_hex(0xFF4041), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_LabelWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_PanelMain);
lv_obj_set_width( ui_Panel3, 470);
lv_obj_set_height( ui_Panel3, 138);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, 3 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel5, 150);
lv_obj_set_height( ui_Panel5, 130);
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcFan = lv_arc_create(ui_Panel5);
lv_obj_set_width( ui_ArcFan, 100);
lv_obj_set_height( ui_ArcFan, 99);
lv_obj_set_align( ui_ArcFan, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ArcFan,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_ArcFan, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ArcFan, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_ArcFan, 0,9);
lv_arc_set_value(ui_ArcFan, 0);

lv_obj_set_style_arc_color(ui_ArcFan, lv_color_hex(0xA1A1B1), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcFan, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcFan, lv_color_hex(0xA1A1B1), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcFan, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelFan = lv_label_create(ui_ArcFan);
lv_obj_set_width( ui_LabelFan, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFan, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelFan, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelFan,"%0");
lv_obj_set_style_text_font(ui_LabelFan, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel6, 150);
lv_obj_set_height( ui_Panel6, 130);
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label3, 131);
lv_obj_set_height( ui_Label3, 74);
lv_obj_set_x( ui_Label3, 8 );
lv_obj_set_y( ui_Label3, -18 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"");
lv_obj_set_style_bg_img_src( ui_Label3, &ui_img_1215880664, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_LabelPm = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_LabelPm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPm, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPm,"0 um/ml");
lv_obj_set_style_text_font(ui_LabelPm, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_PanelMain);
lv_obj_set_width( ui_Panel4, 470);
lv_obj_set_height( ui_Panel4, 46);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, 98 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Panel4);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 50);
lv_obj_set_x( ui_Button4, -322 );
lv_obj_set_y( ui_Button4, -59 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button4, &ui_img_schedule_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_btn_create(ui_Panel4);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 54);
lv_obj_set_x( ui_Button5, 83 );
lv_obj_set_y( ui_Button5, 84 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button5, &ui_img_357916539, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
