// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: air_quality

#include "ui.h"

void ui_ScreenWifiConf_screen_init(void)
{
ui_ScreenWifiConf = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenWifiConf, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonWifiSave = lv_btn_create(ui_ScreenWifiConf);
lv_obj_set_width( ui_ButtonWifiSave, 115);
lv_obj_set_height( ui_ButtonWifiSave, 35);
lv_obj_set_x( ui_ButtonWifiSave, 170 );
lv_obj_set_y( ui_ButtonWifiSave, -63 );
lv_obj_set_align( ui_ButtonWifiSave, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonWifiSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonWifiSave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_ButtonWifiSave);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 1 );
lv_obj_set_y( ui_Label7, 1 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Save");

ui_ButtonWifiBack = lv_btn_create(ui_ScreenWifiConf);
lv_obj_set_width( ui_ButtonWifiBack, 115);
lv_obj_set_height( ui_ButtonWifiBack, 35);
lv_obj_set_x( ui_ButtonWifiBack, 170 );
lv_obj_set_y( ui_ButtonWifiBack, -109 );
lv_obj_set_align( ui_ButtonWifiBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonWifiBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonWifiBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonWifiBack, lv_color_hex(0xEEDE00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonWifiBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_ButtonWifiBack);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Back");

ui_Keyboard1 = lv_keyboard_create(ui_ScreenWifiConf);
lv_obj_set_width( ui_Keyboard1, 466);
lv_obj_set_height( ui_Keyboard1, 157);
lv_obj_set_x( ui_Keyboard1, -2 );
lv_obj_set_y( ui_Keyboard1, 53 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_DropdownWifiSsid = lv_dropdown_create(ui_ScreenWifiConf);
lv_dropdown_set_options( ui_DropdownWifiSsid, "" );
lv_obj_set_width( ui_DropdownWifiSsid, 266);
lv_obj_set_height( ui_DropdownWifiSsid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DropdownWifiSsid, -97 );
lv_obj_set_y( ui_DropdownWifiSsid, -105 );
lv_obj_set_align( ui_DropdownWifiSsid, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownWifiSsid, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_TextAreaWifiPass = lv_textarea_create(ui_ScreenWifiConf);
lv_obj_set_width( ui_TextAreaWifiPass, 270);
lv_obj_set_height( ui_TextAreaWifiPass, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextAreaWifiPass, -95 );
lv_obj_set_y( ui_TextAreaWifiPass, -59 );
lv_obj_set_align( ui_TextAreaWifiPass, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaWifiPass,"Password");
lv_textarea_set_one_line(ui_TextAreaWifiPass,true);



ui_Button3 = lv_btn_create(ui_ScreenWifiConf);
lv_obj_set_width( ui_Button3, 48);
lv_obj_set_height( ui_Button3, 84);
lv_obj_set_x( ui_Button3, 73 );
lv_obj_set_y( ui_Button3, -84 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x14AB2F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button3, &ui_img_534919753, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_ButtonWifiSave, ui_event_ButtonWifiSave, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonWifiBack, ui_event_ButtonWifiBack, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard1,ui_TextAreaWifiPass);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
